[package]
name = "cw-osmo-proto"
version = "0.1.0"
authors = ["Giancarlo Salas <me@giansalex.dev>"]
edition = "2018"
description = "Proto helpers"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"
cosmwasm-std = { version = "1.0.0-beta5", features = ["stargate"] }
