[package]
name = "cw-osmo-proto"
version = "0.1.0"
authors = ["Giancarlo Salas <me@giansalex.dev>"]
edition = "2018"
description = "Osmosis proto helpers"
repository = "https://github.com/disperze/cw-osmo"
license = "MIT"
keywords = ["osmosis", "protobuf", "cosmwasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"
prost-types = "0.9"
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
